[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "donut-decryptor"
dynamic = ["version"]
description = "Decryptor for files containing Donut shellcode"
readme = "README.md"
requires-python = ">=3.9"
keywords = []
license = "BSD-3-Clause"
authors = [
    { name = "Volexity", email = "threatintel@volexity.com" },
]
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Security",
]
dependencies = [
    "aplib ~= 0.6",
    "chaskey ~= 0.0.4",
    "lznt1 ~= 0.2",
    "yara-python ~= 4.5",
]

[project.scripts]
donut-decryptor = "donut_decryptor.cli:run"

[project.urls]
Documentation = "https://github.com/volexity/donut-decryptor/blob/main/README.md"
Issues = "https://github.com/volexity/donut-decryptor/issues"
Source = "https://github.com/volexity/donut-decryptor"

[tool.coverage.paths]
donut_decryptor = ["src/donut_decryptor", "*/donut-decryptor/src/donut_decryptor"]
tests = ["tests", "*/donut-decryptor/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]

[tool.coverage.run]
source_pkgs = ["donut_decryptor", "tests"]
branch = true
parallel = true
omit = [
  "src/donut_decryptor/_version.py",
]

[tool.hatch.build.hooks.vcs]
version-file = "src/donut_decryptor/_version.py"

[tool.hatch.envs.default]
extra-dependencies = [
  "mypy~=1.0",
]

[tool.hatch.envs.hatch-static-analysis]
config-path = "none"
dependencies = ["ruff~=0.14"]

[tool.hatch.envs.hatch-test]
extra-dependencies = [
  "py7zr ~= 1.0",
]

[[tool.hatch.envs.hatch-test.matrix]]
python = ["3.14", "3.13", "3.12", "3.11", "3.10", "3.9"]

[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/donut_decryptor}"

[tool.hatch.version]
source = "vcs"

[[tool.mypy.overrides]]
module = [
  "aplib.*",
  "lznt1.*",
  "yara.*"
]
ignore_missing_imports = true

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "COM812",
  "ISC001",
  "FIX001",
  "FIX002",
  "FIX003",
  "FIX004",
  "TD001",
  "TD002",
  "TD003"
]
pydocstyle = { convention = 'google' }

[tool.ruff.lint.per-file-ignores]
"**/tests/**/*" = [
  "D",
  "S",
]

[tool.ruff.lint.isort]
known-first-party = ["donut_decryptor"]
